import java.awt.Color;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author orion
 */
public class View extends javax.swing.JPanel {
    
    private JButton[] firstRow;
    private JButton[] secondRow;
    private JButton[] thirdRow;
    private JButton[][] board = {firstRow, secondRow, thirdRow};
    
    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        // Init JButton array
        JButton[] temp1 = {qKey, wKey, eKey, rKey, tKey, yKey, uKey, iKey, oKey,
            pKey, leftSquareBracketKey, rightSquareBracketKey, forwardSlashKey};
        JButton[] temp2 = {aKey, sKey, dKey, fKey, gKey, hKey, jKey, kKey, lKey,
            semicolonKey, singleQuoteKey, returnKey};
        JButton[] temp3 = {zKey, xKey, cKey, vKey, bKey, nKey, mKey, commaKey, 
            dotKey, backSlashKey};
        firstRow = temp1;
        secondRow = temp2;
        thirdRow = temp3;
    }
    
    public boolean setMoles(Keyboard board) {
        Keyboard.Keyrow[] rows = board.getKeyrows();
        for(int i = 0; i < this.board.length; i++) {
            for(int moleKeyIndex: rows[i].getKeys()) {
                this.board[i][moleKeyIndex].setBackground(Color.red);
            }
        }
        return true; // Return true upon success
    }
    
    public Keyboard getBoard() {
        throw new UnsupportedOperationException();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keyBoard = new javax.swing.JPanel();
        firstRowPanel = new javax.swing.JPanel();
        rightSquareBracketKey = new javax.swing.JButton();
        leftSquareBracketKey = new javax.swing.JButton();
        pKey = new javax.swing.JButton();
        oKey = new javax.swing.JButton();
        iKey = new javax.swing.JButton();
        yKey = new javax.swing.JButton();
        tKey = new javax.swing.JButton();
        rKey = new javax.swing.JButton();
        eKey = new javax.swing.JButton();
        wKey = new javax.swing.JButton();
        qKey = new javax.swing.JButton();
        uKey = new javax.swing.JButton();
        forwardSlashKey = new javax.swing.JButton();
        secondRowPanel = new javax.swing.JPanel();
        returnKey = new javax.swing.JButton();
        singleQuoteKey = new javax.swing.JButton();
        semicolonKey = new javax.swing.JButton();
        lKey = new javax.swing.JButton();
        kKey = new javax.swing.JButton();
        hKey = new javax.swing.JButton();
        gKey = new javax.swing.JButton();
        fKey = new javax.swing.JButton();
        dKey = new javax.swing.JButton();
        sKey = new javax.swing.JButton();
        aKey = new javax.swing.JButton();
        jKey = new javax.swing.JButton();
        thirdRowPanel = new javax.swing.JPanel();
        zKey = new javax.swing.JButton();
        xKey = new javax.swing.JButton();
        cKey = new javax.swing.JButton();
        vKey = new javax.swing.JButton();
        bKey = new javax.swing.JButton();
        nKey = new javax.swing.JButton();
        mKey = new javax.swing.JButton();
        commaKey = new javax.swing.JButton();
        dotKey = new javax.swing.JButton();
        backSlashKey = new javax.swing.JButton();
        whacAWholeIconLabel = new javax.swing.JLabel();

        rightSquareBracketKey.setText("]");

        leftSquareBracketKey.setText("[");

        pKey.setText("P");

        oKey.setText("O");

        iKey.setText("I");

        yKey.setText("Y");

        tKey.setText("T");

        rKey.setText("R");

        eKey.setText("E");

        wKey.setText("W");

        qKey.setText("Q");

        uKey.setText("U");

        forwardSlashKey.setText("\\");

            javax.swing.GroupLayout firstRowPanelLayout = new javax.swing.GroupLayout(firstRowPanel);
            firstRowPanel.setLayout(firstRowPanelLayout);
            firstRowPanelLayout.setHorizontalGroup(
                firstRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstRowPanelLayout.createSequentialGroup()
                    .addContainerGap(38, Short.MAX_VALUE)
                    .addComponent(qKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(wKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(eKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(rKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(tKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(yKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(uKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(iKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(oKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(pKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(leftSquareBracketKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(rightSquareBracketKey, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(forwardSlashKey, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            firstRowPanelLayout.setVerticalGroup(
                firstRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstRowPanelLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(firstRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rightSquareBracketKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(oKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(leftSquareBracketKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(forwardSlashKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6))
            );

            returnKey.setText("return");

            singleQuoteKey.setText("'");

            semicolonKey.setText(";");

            lKey.setText("L");

            kKey.setText("K");

            hKey.setText("H");

            gKey.setText("G");

            fKey.setText("F");

            dKey.setText("D");

            sKey.setText("S");

            aKey.setText("A");

            jKey.setText("J");

            javax.swing.GroupLayout secondRowPanelLayout = new javax.swing.GroupLayout(secondRowPanel);
            secondRowPanel.setLayout(secondRowPanelLayout);
            secondRowPanelLayout.setHorizontalGroup(
                secondRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondRowPanelLayout.createSequentialGroup()
                    .addContainerGap(37, Short.MAX_VALUE)
                    .addComponent(aKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(sKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(dKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(fKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(gKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(hKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(kKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(lKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(semicolonKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(singleQuoteKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(returnKey, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0))
            );
            secondRowPanelLayout.setVerticalGroup(
                secondRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondRowPanelLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(secondRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(returnKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(semicolonKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(singleQuoteKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6))
            );

            zKey.setText("Z");

            xKey.setText("X");

            cKey.setText("C");

            vKey.setText("V");

            bKey.setText("B");

            nKey.setText("N");

            mKey.setText("M");

            commaKey.setText(",");

            dotKey.setText(".");

            backSlashKey.setText("/");

            whacAWholeIconLabel.setText("地鼠");

            javax.swing.GroupLayout thirdRowPanelLayout = new javax.swing.GroupLayout(thirdRowPanel);
            thirdRowPanel.setLayout(thirdRowPanelLayout);
            thirdRowPanelLayout.setHorizontalGroup(
                thirdRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(thirdRowPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(xKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(cKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(vKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(bKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(nKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(mKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(commaKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(dotKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(backSlashKey, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(whacAWholeIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0))
            );
            thirdRowPanelLayout.setVerticalGroup(
                thirdRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thirdRowPanelLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(thirdRowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(zKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(xKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(commaKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dotKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backSlashKey, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(whacAWholeIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6))
            );

            javax.swing.GroupLayout keyBoardLayout = new javax.swing.GroupLayout(keyBoard);
            keyBoard.setLayout(keyBoardLayout);
            keyBoardLayout.setHorizontalGroup(
                keyBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(keyBoardLayout.createSequentialGroup()
                    .addContainerGap(30, Short.MAX_VALUE)
                    .addGroup(keyBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(secondRowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(firstRowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thirdRowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(31, Short.MAX_VALUE))
            );
            keyBoardLayout.setVerticalGroup(
                keyBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(keyBoardLayout.createSequentialGroup()
                    .addContainerGap(34, Short.MAX_VALUE)
                    .addComponent(firstRowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(secondRowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(thirdRowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(59, Short.MAX_VALUE)
                    .addComponent(keyBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(60, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(113, Short.MAX_VALUE)
                    .addComponent(keyBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(60, Short.MAX_VALUE))
            );
        }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aKey;
    private javax.swing.JButton bKey;
    private javax.swing.JButton backSlashKey;
    private javax.swing.JButton cKey;
    private javax.swing.JButton commaKey;
    private javax.swing.JButton dKey;
    private javax.swing.JButton dotKey;
    private javax.swing.JButton eKey;
    private javax.swing.JButton fKey;
    private javax.swing.JPanel firstRowPanel;
    private javax.swing.JButton forwardSlashKey;
    private javax.swing.JButton gKey;
    private javax.swing.JButton hKey;
    private javax.swing.JButton iKey;
    private javax.swing.JButton jKey;
    private javax.swing.JButton kKey;
    private javax.swing.JPanel keyBoard;
    private javax.swing.JButton lKey;
    private javax.swing.JButton leftSquareBracketKey;
    private javax.swing.JButton mKey;
    private javax.swing.JButton nKey;
    private javax.swing.JButton oKey;
    private javax.swing.JButton pKey;
    private javax.swing.JButton qKey;
    private javax.swing.JButton rKey;
    private javax.swing.JButton returnKey;
    private javax.swing.JButton rightSquareBracketKey;
    private javax.swing.JButton sKey;
    private javax.swing.JPanel secondRowPanel;
    private javax.swing.JButton semicolonKey;
    private javax.swing.JButton singleQuoteKey;
    private javax.swing.JButton tKey;
    private javax.swing.JPanel thirdRowPanel;
    private javax.swing.JButton uKey;
    private javax.swing.JButton vKey;
    private javax.swing.JButton wKey;
    private javax.swing.JLabel whacAWholeIconLabel;
    private javax.swing.JButton xKey;
    private javax.swing.JButton yKey;
    private javax.swing.JButton zKey;
    // End of variables declaration//GEN-END:variables
}
